zap:
  level: 'info'
  filename: 'logs/app.log'
  max-size: 500
  max-backups: 3
  max-age: 28
  compress: true

jwt:
  key: 'roro'
  timeout: 24

mysql:
  addr: '120.79.157.49:3306'
  username: 'root'
  password: '123456'
  protocal: 'tcp'
  database: 'test'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'

redis:
  addr: '39.107.29.66:6379'
  password: 'cc123/.,'
  db: 0

mongodb:
  addr: '120.79.157.49:27017'
  database: 'test'

qiniu:
  access-key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
  secret-key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
  img-path: 'http://qmplusimg.henrongyi.top'
  bucket: 'qm-plus-img'
  zone: 'ZoneHuadong'
  use-https: false
  use-cdn-domains: false