mysql:
  username: 'root'
  password: 'Zhangbincheng0'
  protocal: 'tcp'
  addr: 'www.littleredhat1997.com:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  database: 'test'

redis:
  addr: 'www.littleredhat1997.com:6379'
  password: 'Zhangbincheng0'
  db: 0

mongodb:
  addr: '120.79.157.49:27017'
  password: 'Zhangbincheng0'
  database: 'test'

qiniu:
  zone: 'ZoneHuadong'
  bucket: 'qm-plus-img'
  img-path: 'http://qmplusimg.henrongyi.top'
  use-https: false
  access-key: '25j8dYBZ2wuiy0yhwShytjZDTX662b8xiFguwxzZ'
  secret-key: 'pgdbqEsf7ooZh7W3xokP833h3dZ_VecFXPDeG5JY'
  use-cdn-domains: false

jwt:
  key: 'roro'
  timeout: 24

zap:
  level: 'info'
  format: 'console'
  prefix: '[GO-VUE]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true